-- 0017_synthetic_demo_data.sql
-- Synthetic demo data marking + the per-energy-source change view.
--
-- WHY THIS EXISTS
-- The professor demo needs a large, clearly-labelled fictional cohort run
-- through the REAL analytics engine (migration 0012 views), not through a
-- parallel calculation. Two things were missing for that:
--
--   1. a durable, queryable marker separating synthetic rows from real
--      student data. A naming convention on emails is not enough — once a
--      figure reaches a chart or an export, the provenance has to travel
--      with the row, not with a filename.
--   2. a view expressing per-energy-source A1 -> A2 totals with absolute
--      and relative change. Everything else the demo needs already exists
--      in 0012; this is the one genuinely new aggregate.
--
-- NO NEW TABLES, so no new RLS policies are required (.claude/rules/db.md):
-- is_synthetic is a column on tables that already carry student-data
-- policies, and the new view is security_invoker like every other 0012
-- view, so the caller's own RLS decides what it returns.
--
-- NEUTRALITY: nothing here ranks 0 above 1 or 1 above 0. "Change" is a
-- count difference in either direction; direction is reported, never
-- judged (.claude/rules/analytics.md).

-- ============================================================
-- 1. is_synthetic markers.
--
-- Placed on the four tables a demo cohort actually writes: the person, the
-- enrolment, the attempt, and the answer. Classes, assignments, questions
-- and mappings are deliberately NOT marked — the demo reuses the real,
-- already-imported assignments and the existing approved mappings and must
-- never create or alter them.
--
-- `not null default false` means every existing row is real by default,
-- which is the safe direction to be wrong in: a real row can never be
-- silently reclassified as demo data by this migration.
-- ============================================================

alter table public.profiles
  add column if not exists is_synthetic boolean not null default false;

alter table public.class_members
  add column if not exists is_synthetic boolean not null default false;

alter table public.assignment_attempts
  add column if not exists is_synthetic boolean not null default false;

alter table public.responses
  add column if not exists is_synthetic boolean not null default false;

comment on column public.profiles.is_synthetic is
  'True only for fictional demo accounts generated by scripts/seed-demo-analytics.ts. Never set on a real person.';
comment on column public.class_members.is_synthetic is
  'True only for enrolments of fictional demo accounts.';
comment on column public.assignment_attempts.is_synthetic is
  'True only for attempts belonging to fictional demo accounts.';
comment on column public.responses.is_synthetic is
  'True only for responses belonging to fictional demo accounts. response_value is still constrained to 0/1/NULL — synthetic data obeys every real constraint.';

-- Partial indexes: the only interesting query is "which rows are
-- synthetic", and synthetic rows are the minority in any class that has
-- real data, so indexing the false side would be wasted space.
create index if not exists profiles_synthetic_idx
  on public.profiles (id) where is_synthetic;
create index if not exists class_members_synthetic_idx
  on public.class_members (class_id) where is_synthetic;
create index if not exists assignment_attempts_synthetic_idx
  on public.assignment_attempts (assignment_id) where is_synthetic;
create index if not exists responses_synthetic_idx
  on public.responses (assignment_id) where is_synthetic;

-- ============================================================
-- 2. class_synthetic_census — how much of a class is demo data.
--
-- The demo dashboard must never describe real students as synthetic, and
-- must never quietly fold real students into a figure it labels "demo".
-- This view is what lets the page state the split honestly: it reports
-- BOTH counts, so a mixed class is visibly mixed rather than rounded to
-- whichever answer is convenient.
-- ============================================================

create or replace view public.class_synthetic_census
with (security_invoker = on) as
select
  cm.class_id,
  count(*) as student_count,
  count(*) filter (where cm.is_synthetic) as synthetic_student_count,
  count(*) filter (where not cm.is_synthetic) as real_student_count
from public.class_members cm
where cm.member_role = 'STUDENT'
  and cm.status = 'ACTIVE'
group by cm.class_id;

grant select on public.class_synthetic_census to authenticated, service_role;

-- ============================================================
-- 3. energy_source_assignment_change — per-energy-source totals for both
--    assignments, with absolute and relative change.
--
-- Built ON TOP OF the existing 0012 aggregate
-- (energy_source_response_summary), not beside it: the per-assignment
-- counts, percentages, consensus and entropy are computed exactly once, in
-- 0012, and this view only pivots A1 against A2 and differences them.
--
-- KEY JOIN — energy_source labels are stored VERBATIM from the source
-- spreadsheets and are NOT trimmed (lib/imports/parse-grid.ts keeps the
-- wording byte-for-byte on purpose). Assignment 2's sheet has "Solar "
-- with a trailing space where Assignment 1 has "Solar". Joining on the raw
-- label would silently split one energy source into two one-sided rows and
-- report "—" for a comparison that genuinely exists. So the JOIN KEY is
-- btrim(energy_source), while both raw labels are carried through
-- unchanged so the original wording is never lost or invented. Where more
-- than one raw label collapses into one key, every distinct raw label is
-- listed (' | '-joined) rather than one being picked and the others
-- dropped.
--
-- ONE-SIDED SOURCES ARE REAL: Assignment 1 has Thermal/Fusion/Kinetic/
-- Magnetic; Assignment 2 has Geothermal/Tidal/Wave/Garbage. Those rows
-- keep NULL on the absent side and NULL for every derived change. They are
-- not dropped (dropping them would hide half the instrument) and they are
-- not zero-filled (a source that was never asked about did not score zero).
--
-- FORMULAS
--   ones_absolute_change  = a2_ones - a1_ones          (a count difference)
--   ones_relative_change  = (a2_ones - a1_ones) / a1_ones
--                           => NULL when a1_ones = 0 (ZERO BASELINE) or
--                              when either side is absent. Never a
--                              divide-by-zero, never a fabricated 0% or
--                              100%. The UI renders NULL as "—".
--   pct_point_shift       = %1 in A2 - %1 in A1
--                           docs/ANALYTICS_DEFINITIONS.md verbatim.
--
-- ones_relative_change and pct_point_shift are DIFFERENT MEASUREMENTS and
-- the UI must not present one as the other: the first is relative to the
-- A1 count and is unbounded, the second is a difference of two rates in
-- percentage points. Both are direction-only descriptions of how a group
-- of opinions moved. Neither is a rate of change of opinion "quality",
-- because no such quantity exists in this system.
-- ============================================================

create or replace view public.energy_source_assignment_change
with (security_invoker = on) as
with per_side as (
  select
    es.class_id,
    btrim(es.energy_source) as energy_source,
    es.energy_source as energy_source_raw,
    a.sequence_number,
    es.question_count,
    es.answered,
    es.zeros,
    es.ones
  from public.energy_source_response_summary es
  join public.assignments a on a.id = es.assignment_id
  where a.sequence_number in (1, 2)
),
sides as (
  select
    p.class_id,
    p.energy_source,
    string_agg(distinct p.energy_source_raw, ' | ') filter (where p.sequence_number = 1) as a1_energy_source_raw,
    string_agg(distinct p.energy_source_raw, ' | ') filter (where p.sequence_number = 2) as a2_energy_source_raw,
    sum(p.question_count) filter (where p.sequence_number = 1) as a1_question_count,
    sum(p.question_count) filter (where p.sequence_number = 2) as a2_question_count,
    sum(p.answered) filter (where p.sequence_number = 1) as a1_answered,
    sum(p.answered) filter (where p.sequence_number = 2) as a2_answered,
    sum(p.zeros) filter (where p.sequence_number = 1) as a1_zeros,
    sum(p.zeros) filter (where p.sequence_number = 2) as a2_zeros,
    sum(p.ones) filter (where p.sequence_number = 1) as a1_ones,
    sum(p.ones) filter (where p.sequence_number = 2) as a2_ones
  from per_side p
  group by p.class_id, p.energy_source
)
select
  s.*,
  (s.a1_answered is not null and s.a2_answered is not null) as both_sides_present,
  case when s.a1_answered > 0 then s.a1_ones::float8 / s.a1_answered end as a1_pct_one,
  case when s.a2_answered > 0 then s.a2_ones::float8 / s.a2_answered end as a2_pct_one,
  case
    when s.a1_ones is not null and s.a2_ones is not null
    then s.a2_ones - s.a1_ones
  end as ones_absolute_change,
  -- Zero baseline (or an absent side) yields NULL, deliberately.
  case
    when s.a1_ones > 0 and s.a2_ones is not null
    then (s.a2_ones - s.a1_ones)::float8 / s.a1_ones
  end as ones_relative_change,
  case
    when s.a1_answered > 0 and s.a2_answered > 0
    then (s.a2_ones::float8 / s.a2_answered) - (s.a1_ones::float8 / s.a1_answered)
  end as pct_point_shift
from sides s;

grant select on public.energy_source_assignment_change to authenticated, service_role;

comment on view public.energy_source_assignment_change is
  'Per energy source, Assignment 1 vs Assignment 2 response totals with absolute and relative change. Joined on btrim(energy_source) because source labels are stored verbatim; raw labels preserved. Relative change is NULL on a zero baseline or a one-sided source, never zero and never a divide-by-zero.';
