import type { SupabaseClient } from "@supabase/supabase-js";
import { MEASURES, type QueryDefinition } from "@/lib/query-builder/schema";
import { DIMENSIONS } from "@/lib/query-builder/schema";

/**
 * The provenance block every export carries, per the Phase 9 spec:
 * class name, assignment names, generation timestamp, active filters,
 * metric definitions, and mapping versions.
 *
 * It exists so a spreadsheet or PDF that outlives this session can still
 * be read correctly — in particular so nobody compares two exports taken
 * against different mapping versions without noticing.
 */

export interface MappingVersionNote {
  name: string;
  version: number;
  status: string;
  approved: boolean;
}

export interface ExportMetadata {
  className: string;
  assignmentNames: string[];
  generatedAt: string;
  generatedBy: string;
  activeFilters: string[];
  metricDefinitions: Array<{ label: string; definition: string }>;
  mappingVersions: MappingVersionNote[];
  notes: string[];
}

/** Neutral-tone note carried by every export (Section 16 rule). */
export const NEUTRALITY_NOTE =
  "These are descriptive statistics about opinions. No value here is a grade, a score, " +
  "or a correctness judgement, and no answer is more correct than another.";

export const APPROVAL_NOTE =
  "Analytics and transition figures include approved mappings only. Unapproved, rejected, " +
  "and superseded mappings contribute to no figure in this export.";

export function describeFilters(query: QueryDefinition | null): string[] {
  if (!query) return ["None"];
  const parts: string[] = [];
  parts.push(`Dataset: ${query.dataset}`);
  parts.push(`Measure: ${MEASURES[query.measure]?.label ?? query.measure}`);
  if (query.dimensions.length > 0) {
    parts.push(
      `Grouped by: ${query.dimensions.map((d) => DIMENSIONS[d]?.label ?? d).join(", ")}`
    );
  }
  for (const filter of query.filters) {
    parts.push(`${DIMENSIONS[filter.dimension]?.label ?? filter.dimension} = ${filter.value}`);
  }
  return parts.length > 0 ? parts : ["None"];
}

/**
 * Builds the metadata block. Reads mapping versions through
 * `question_mappings` (the professor's own inventory — RLS scopes it to
 * their classes) and records approval status per row, so a reader can see
 * which versions were live when the export was taken.
 */
export async function buildExportMetadata(
  supabase: SupabaseClient,
  options: {
    classId: string;
    className: string;
    generatedBy: string;
    query?: QueryDefinition | null;
    measureIds?: Array<keyof typeof MEASURES>;
  }
): Promise<ExportMetadata> {
  const { data: assignments, error: assignmentsError } = await supabase
    .from("assignments")
    .select("title, sequence_number")
    .eq("class_id", options.classId)
    .order("sequence_number");
  if (assignmentsError) {
    throw new Error(`could not load assignments for export metadata: ${assignmentsError.message}`);
  }

  const { data: mappings, error: mappingsError } = await supabase
    .from("question_mappings")
    .select("mapping_name, version, mapping_status, professor_approved")
    .eq("class_id", options.classId)
    .order("mapping_name")
    .returns<
      Array<{
        mapping_name: string;
        version: number;
        mapping_status: string;
        professor_approved: boolean;
      }>
    >();
  if (mappingsError) {
    throw new Error(`could not load mapping versions for export metadata: ${mappingsError.message}`);
  }

  const measureIds =
    options.measureIds ??
    (options.query ? [options.query.measure] : (Object.keys(MEASURES) as Array<keyof typeof MEASURES>));

  return {
    className: options.className,
    assignmentNames: (assignments ?? []).map((a) => a.title),
    generatedAt: new Date().toISOString(),
    generatedBy: options.generatedBy,
    activeFilters: describeFilters(options.query ?? null),
    metricDefinitions: measureIds.map((id) => ({
      label: MEASURES[id].label,
      definition: MEASURES[id].definition,
    })),
    mappingVersions: (mappings ?? []).map((m) => ({
      name: m.mapping_name,
      version: m.version,
      status: m.mapping_status,
      approved: m.professor_approved,
    })),
    notes: [NEUTRALITY_NOTE, APPROVAL_NOTE],
  };
}

/** Flat key/value lines — the shape CSV, Excel, and PDF headers all use. */
export function metadataLines(metadata: ExportMetadata): Array<[string, string]> {
  const approvedVersions = metadata.mappingVersions.filter((m) => m.approved);
  return [
    ["Class", metadata.className],
    ["Assignments", metadata.assignmentNames.join(" | ") || "None"],
    ["Generated at", metadata.generatedAt],
    ["Generated by", metadata.generatedBy],
    ["Active filters", metadata.activeFilters.join(" | ")],
    [
      "Approved mapping versions",
      approvedVersions.length > 0
        ? approvedVersions.map((m) => `${m.name} v${m.version}`).join(" | ")
        : "None approved",
    ],
    [
      "Metric definitions",
      metadata.metricDefinitions.map((m) => `${m.label}: ${m.definition}`).join(" "),
    ],
    ["Notes", metadata.notes.join(" ")],
  ];
}

/** Fixed height of the provenance block written above every sheet/table. */
export const METADATA_ROW_COUNT = 8;
