import type { SupabaseClient } from "@supabase/supabase-js";
import { MEASURES, type QueryDefinition } from "@/lib/query-builder/schema";
import { DIMENSIONS } from "@/lib/query-builder/schema";

/**
 * The provenance block every export carries, per the Phase 9 spec:
 * class name, assignment names, generation timestamp, active filters, and
 * metric definitions.
 *
 * It exists so a spreadsheet or PDF that outlives this session can still
 * be read correctly a year later, without the page it came from.
 */

export interface ExportMetadata {
  className: string;
  assignmentNames: string[];
  generatedAt: string;
  generatedBy: string;
  activeFilters: string[];
  metricDefinitions: Array<{ label: string; definition: string }>;
  notes: string[];
}

/** Neutral-tone note carried by every export (Section 16 rule). */
export const NEUTRALITY_NOTE =
  "These are descriptive statistics about opinions. No value here is a grade, a score, " +
  "or a correctness judgement, and no answer is more correct than another.";

export const SINGLE_ASSIGNMENT_NOTE =
  "Every figure in this export describes ONE assignment on its own. This export carries no " +
  "per-student comparison between the two assignments.";

export function describeFilters(query: QueryDefinition | null): string[] {
  if (!query) return ["None"];
  const parts: string[] = [];
  parts.push(`Dataset: ${query.dataset}`);
  parts.push(`Measure: ${MEASURES[query.measure]?.label ?? query.measure}`);
  if (query.dimensions.length > 0) {
    parts.push(
      `Grouped by: ${query.dimensions.map((d) => DIMENSIONS[d]?.label ?? d).join(", ")}`
    );
  }
  for (const filter of query.filters) {
    parts.push(`${DIMENSIONS[filter.dimension]?.label ?? filter.dimension} = ${filter.value}`);
  }
  return parts.length > 0 ? parts : ["None"];
}

/** Builds the metadata block. Reads only the caller's own class, through
 *  their RLS-scoped client. */
export async function buildExportMetadata(
  supabase: SupabaseClient,
  options: {
    classId: string;
    className: string;
    generatedBy: string;
    query?: QueryDefinition | null;
    measureIds?: Array<keyof typeof MEASURES>;
  }
): Promise<ExportMetadata> {
  const { data: assignments, error: assignmentsError } = await supabase
    .from("assignments")
    .select("title, sequence_number")
    .eq("class_id", options.classId)
    .order("sequence_number");
  if (assignmentsError) {
    throw new Error(`could not load assignments for export metadata: ${assignmentsError.message}`);
  }

  const measureIds =
    options.measureIds ??
    (options.query ? [options.query.measure] : (Object.keys(MEASURES) as Array<keyof typeof MEASURES>));

  return {
    className: options.className,
    assignmentNames: (assignments ?? []).map((a) => a.title),
    generatedAt: new Date().toISOString(),
    generatedBy: options.generatedBy,
    activeFilters: describeFilters(options.query ?? null),
    metricDefinitions: measureIds.map((id) => ({
      label: MEASURES[id].label,
      definition: MEASURES[id].definition,
    })),
    notes: [NEUTRALITY_NOTE, SINGLE_ASSIGNMENT_NOTE],
  };
}

/** Flat key/value lines — the shape CSV, Excel, and PDF headers all use. */
export function metadataLines(metadata: ExportMetadata): Array<[string, string]> {
  return [
    ["Class", metadata.className],
    ["Assignments", metadata.assignmentNames.join(" | ") || "None"],
    ["Generated at", metadata.generatedAt],
    ["Generated by", metadata.generatedBy],
    ["Active filters", metadata.activeFilters.join(" | ")],
    [
      "Metric definitions",
      metadata.metricDefinitions.map((m) => `${m.label}: ${m.definition}`).join(" "),
    ],
    ["Notes", metadata.notes.join(" ")],
  ];
}

/** Fixed height of the provenance block written above every sheet/table.
 *  Must equal metadataLines()'s row count. */
export const METADATA_ROW_COUNT = 7;
